### ISSUE TITLE
Add debug or logging

### ISSUE THREAD

**Issue by jstewmc** [jstewmc/gravity#10]
We should add the ability for Gravity to log the definitions and additions to the project in order to make debugging easier, especially when something is overwritten or defined outside of its expected package. 

Otherwise, with the ability for anyone to set services and configuration anywhere, it may be very difficult to understand what happened when something goes wrong.

**Comment by jstewmc** [comment]
Rather than a special debug mode, may we just support logging the different alias, deprecate, set, and get method calls. There is a [PSR-3 logger interface](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md).

**Comment by jack-clayton** [comment]
It would be great if Gravity could load the logger service from the project (i.e., let people inject the logger into the manager without actually injecting it). After the project filesystem has been loaded, load the log:

```
// in the Gravity manager...
private function loadLogger(): void
{
    if ($this->project->has('Jstewmc\Gravity\Logger')) {
        $this->logger = $this->getDefinition('Jstewmc\Gravity\Logger');
    }
}
```

Then, we can just add logging events to the manager's `get()`, `set()`, `alias()`, and `deprecate()` methods using PHP's shorthand evaluation:

```php 
// ... do something 

$this->log && $this->log->info("Hello world");

// ... do something
```

Hmm, this might be a little circular. I could imagine some services depending on the logger being injected, but the logger has to come after the filesystem load, which has to come after the services are instantiated. It really would be great if Gravity could bootstrap itself haha.
