### ISSUE TITLE
Add support for environment-aware settings and services

### ISSUE THREAD

**Issue by jstewmc** [jstewmc/gravity#30]
We should add support for environment-aware settings and services, where the _environment_ settings and services to take precedence over _global_ ones. For example, this would allow users to configure different database connections in different environments.

I'm thinking we add a `.gravity/environments` directory, and we treat any direct subdirectory as an environment name (e.g., `.gravity/environments/development`, `.gravity/environments/test`, etc). Within the subdirectory, the user is free to organize things however they'd like. 

Then, we accept an`$environment` argument to the _read-filesystem_ service (perhaps it's injected into Gravity's constructor). The _read-filesystem_ service will ignore the `environments` directory on the first pass. However, on the last pass, it would load any directory in the `environments` directory with the filename equal to `$environment`. 

This way, we don't dictate environment names. However, we should still probably provide  a standard set to give developers a backbone that they can depend on. I think the standard `development`, `test`, `staging`, and `production` should work.

**Comment by jstewmc** [comment]
Better yet, Gravity could load the environment from a file anywhere. That would allow users to set it however they choose their environment. Environment directories would have to be skipped until the rest of the filesystem was loaded, though. By then, Gravity should know its evironment (i.e., `$g->get('jstewmc.gravity.environment');`, if it's been set at all.

**Comment by jstewmc** [comment]
Hmm, I don't think we can allow _arbitrary_ environment names. Otherwise, the community can't coordinate their efforts: `testing` vs `test`, `dev` vs `development`, and `prod` versus `production`. 

Instead, I think we should support the standard values: `development`, `test`, `staging`, and `production`.

**Comment by javabudd** [comment]
I think most people would be fine with the basic environment names. Adding complexity to work around that is probably not worth it. Using the standard environment configuration with an option to override with a .local would probably be good enough

**Comment by jstewmc** [comment]
Awesome! Ok, cool. Let's start with those four environments. 

Hmm, should we...

1. Detect the environment, and specify an environment variable (e.g., `GRAVITY_ENV`) the user should define; or,
2. Accept the environment's name as a configuration option (e.g., `(new Gravity())->setEnvironment(Gravity::DEVELOPMENT)->pull()`)? 

The former adds yet another environment variable to the user's application, but the latter may require mapping the user's environment variable names to Gravity's values. 

If we do decide to accept the environment as a configuration variable, we could offer some helper methods to prevent the verbosity of `setEnvironment(Gravity::DEVELOPMENT)`, for example, `inDevelopment()`, `inProduction()`, etc.

**Comment by javabudd** [comment]
I don't see a problem with just including another system environment variable. Trying to map out user options doesn't seem to be worth it when we can have a specific ENV variable (GRAVITY_ENV) that should be easily added to docker/kub configs
