### ISSUE TITLE
Add bootstrap support

### ISSUE THREAD

**Issue by jack-clayton** [jstewmc/gravity#32]
Gravity should be able to bootstrap itself, allowing users to inject services and configuration into it as it starts up like the environment (#30) or the user's preferred logger (#10).

**Comment by jack-clayton** [comment]
@jstewmc (me) has started working on this, and it looks possible. I think we can achieve it by iteratively bootstrapping the project and the manager:

1.  Bootstrap the project with critical services; 
2. Bootstrap a (simplified) manager that can set and get Gravity's services and configuration; 
3. Load bootstrap files; and, 
5. Load the rest of the filesystem.

Maybe we add a new convention - a `bootstrap.php` file? Basically, while Gravity is bootstrapping itself (and before it's loaded the rest of the filesystem), it could find all the `gravity/bootstrap.php` files in the project and load them first, finish bootstrapping itself, then load the rest of the filesystem?

**Comment by jstewmc** [comment]
Closed by #34.
