### ISSUE TITLE
Add PSR-11 compliance

### ISSUE THREAD

**Issue by jstewmc** [jstewmc/gravity#4]
We should support standardized interfaces in order to improve interoperability. [PSR-11](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-11-container.md) is a common interface for dependency injection containers.

**Comment by javabudd** [comment]
I think the base Gravity class should implement the PSR11 Container interface so it plays nice with factories in most frameworks

**Comment by jstewmc** [comment]
Do you mean `Jstewmc\Gravity\Gravity` or the `Jstewmc\Gravity\Manager\Data\Manager` instance it returns? (We can definitely add it to the former.)

I think you're probably right. I'm being too pedantic with the argument types. I want to use the language's latest features like argument type hints, but not if it's going to keep us from working with frameworks.

I'll re-open the issue.

**Comment by javabudd** [comment]
Adding it to the manager was a thought, but then I started thinking about merging the manager logic into the base Gravity class and using that as the container, it seems more fluid IMO but would definitely be a bigger file.

IE.
```
$container = new Gravity();

$container->pull();

$service = $container->get(Foo:class);
$setting = $container->get('foo.bar');
$class = new Class($service, $setting);
```

**Comment by jstewmc** [comment]
Yeah, the Gravity and Manager classes used to be the same. I separated them in the refactor, though. Together they were such a big, gnarly class. It was definitely not SOLID, and it was tough to test. This way, the Gravity class initializes everything, and returns a pretty self-contained Manager. I think they’re better apart, but I’d be all for adding PSR-11 to the Manager.
